// app/layout.tsx
import "@ant-design/v5-patch-for-react-19"; // ✅ Must be first!
import { AntdRegistry } from "@ant-design/nextjs-registry"; // Optional, but recommended
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>{" "}
        {/* ✅ Required for SSR hydration */}
      </body>
    </html>
  );
}
